apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      we: have
      been: imported
      also:
        we: must go deeper
        ola: hello karel
        i: was imported!
      containers:
        - name: redis
          image: redis
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
          we: have
          been: imported
          also:
            we: must go deeper
            ola: hello karel
            i: was imported!
      volumes:
        - name: redis-persistent-storage
          gcePersistentDisk:
            pdName: redis-disk
            fsType: ext4
