apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: redis
  <<: include.yml
  ports:
    - name: redis
      port: 6379
      # nodePort: 32000
      protocol: TCP
---
here: is another yaml within the same file
<<: deep-include.yml